plugins {
    id 'java-library'
    id 'maven-publish'
}

version = mod_version
group = mod_group_id

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    mavenCentral()
}

dependencies {
    compileOnly files('../libs/tianshu_libs-1.0.1.jar')
    compileOnly 'com.google.code.gson:gson:2.10.1'
    compileOnly 'org.apache.commons:commons-compress:1.26.0'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
}

test {
    useJUnitPlatform()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jar {
    archiveBaseName = 'tianshu-common'
}
