plugins {
    id 'java-library'
    id 'maven-publish'
}

version = mod_version
group = mod_group_id

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    mavenCentral()
}

dependencies {
    implementation files('../libs/sherpa-onnx-v1.12.39.jar')
    implementation files('../libs/commons-compress-1.28.0.jar')
    implementation files('../libs/sentencepiece4j-1.0.2.jar')
    implementation files('../libs/onnxruntime-1.24.3.jar')
    implementation files('../libs/pinyin4j-2.5.1.jar')
    implementation 'com.google.code.gson:gson:2.10.1'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jar {
    archiveBaseName = 'tianshu-common'
}
