package com.rheinmetal.tianshu.function.ia.model;

public enum DialogueSessionEventType {
    CONVERSATION_CLAIMED,
    CONVERSATION_RELEASED,
    CONVERSATION_INTERRUPTED,
    CONVERSATION_OWNER_CHANGED,
    CONVERSATION_SESSION_STARTED,
    CONVERSATION_SESSION_FINISHED,
    CONVERSATION_REJECTED,
    CONVERSATION_EXPIRED
}
