package com.rheinmetal.tianshu.protocol.integration;

public enum IntegrationCapability {
    VOICE_TRIGGER,
    DIALOGUE_PARTICIPANT,
    STATE_SUMMARY_PROVIDER,
    STATE_SUMMARY_CONSUMER,
    GUI_RENDER_CONTRIBUTOR,
    SHARED_SNAPSHOT_CONSUMER,
    LIFECYCLE_LISTENER,
    RESOURCE_RELOAD_LISTENER
}
